#!/bin/bash
#
# Inject SSH private key into a DevContainer for git operations.
# Requires: docker, ~/.ssh/id_ed25519 on host
#
# Usage: sendkey <CONTAINER_ID> [CONTAINER_USER]
#

set -ea

function show_usage {
  echo "Usage: $0 [<Argments>]"
  echo ""
  echo "Argments: "
  echo "  [1]: CONTAINER_ID"
  echo "  [2]: CONTAINER_USER (root:default)"
  echo ""
}

SSH_PRIVATEKEY_PATH=~/.ssh/id_ed25519

CONTAINER_ID=$1
CONTAINER_USER="root"
CONTAINER_HOME="/$CONTAINER_USER"

if [ -z "$1" ]; then
  show_usage
  exit 1
fi

if [ -n "$2" ]; then
  CONTAINER_USER=$2
  CONTAINER_HOME=/home/$CONTAINER_USER
fi

CONTAINER_SSH_KEY_PATH=$CONTAINER_HOME/.ssh/id_rsa

set +e

FIND_CONTAINER=$(docker ps | grep "^$CONTAINER_ID" | awk '{print $1}')
FIND_IMAGE=$(docker ps | grep "^$CONTAINER_ID" | awk '{print $2}')

set -e

ERROR=0

if [ -z "$FIND_CONTAINER" ]; then
  FIND_CONTAINER="N/A"
  FIND_IMAGE="N/A"
  ERROR=1
fi

echo "CONTAINER_ID    : $FIND_CONTAINER"
echo "CONTAINER_IMAGE : $FIND_IMAGE"
echo "CONTAINER_USER  : $CONTAINER_USER"

if [ "$ERROR" -eq 1 ]; then
  exit 1
fi

docker cp $SSH_PRIVATEKEY_PATH $CONTAINER_ID:$CONTAINER_SSH_KEY_PATH
docker exec -u root $CONTAINER_ID chmod 600 $CONTAINER_SSH_KEY_PATH
docker exec -u root $CONTAINER_ID chown $CONTAINER_USER:$CONTAINER_USER $CONTAINER_SSH_KEY_PATH
